### ISSUE TITLE
zodbupdate --convert-py3 writes a bad index file

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zodbupdate#21]
I've noticed that `zodbupdate -f Data.fs --pack --convert-py3` (on Python 2) writes a `Data.fs.index` that is then not accepted by ZODB's FileStorage on Python 3, giving me an error:

```
2019-07-24T13:52:16 ERROR ZODB.FileStorage loading index
Traceback (most recent call last):
  File "/home/mg/.buildout/eggs/ZODB-5.5.1-py3.5.egg/ZODB/FileStorage/FileStorage.py", line 465, in _restore_index
    info = fsIndex.load(index_name)
  File "/home/mg/.buildout/eggs/ZODB-5.5.1-py3.5.egg/ZODB/fsIndex.py", line 134, in load
    v = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 83: ordinal not in range(128)
```

Perhaps the conversion script should remove the useless index file if it cannot write a suitable one?

**Comment by dataflake** [comment]
I would be all in favor of letting the target system just create the index itself on startup with the converted ZODB. Seems like the safest thing to do.
