### ISSUE TITLE
zodbupdate --convert-to-py3 fails to handle an IOBucket mapping ints to bytestrings

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zodbupdate#24]
I'm trying to migrate a Zope 3 application to Python 3.  The Data.fs is about 1.2 gigs and has about 3 million objects in it.  The procedure is

    virtualenv -p python2 env && env/bin/pip install zodbupdate -e ~/src/myapp
    env/bin/zodbupdate -f Data.fs --pack --convert-py3

and then I'm doing a dry-run on Python 3 to validate that all the pickles can be loaded

    virtualenv -p python3 env3 && env3/bin/pip install zodbupdate -e ~/src/myapp
    env3/bin/zodbupdate -v -n -f Data.fs

which fails on OID 0x2db225, which is a BTrees.IOBTree.IOBucket instance.  It's not the first IOBucket in the database, but it's the first one that cannot be converted.

The error is in the unpickler and it is a 
```
Traceback (most recent call last):
  File "/home/mg/Private/ivija-staging/env3/lib/python3.5/site-packages/zodbupdate/main.py", line 214, in main
    updater()
  File "/home/mg/Private/ivija-staging/env3/lib/python3.5/site-packages/zodbupdate/update.py", line 82, in __call__
    new = self.processor.rename(current)
  File "/home/mg/Private/ivija-staging/env3/lib/python3.5/site-packages/zodbupdate/serialize.py", line 333, in rename
    data = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 0: ordinal not in range(128)
```

The raw pickle data, post conversion, looks like this:

```
    0: \x80 PROTO      3
    2: c    GLOBAL     'BTrees.IOBTree IOBucket'
   27: q    BINPUT     1
   29: .    STOP
highest protocol among opcodes = 2

   30: \x80 PROTO      3
   32: (    MARK
   33: J        BININT     231506130
   38: U        SHORT_BINSTRING '\x81x\x84Y'
   44: q        BINPUT     2
   46: J        BININT     231506137
   51: U        SHORT_BINSTRING '¾\x84`'
   56: q        BINPUT     3
   58: J        BININT     231506138
   63: U        SHORT_BINSTRING 'â\x84a'
   68: q        BINPUT     4
   70: J        BININT     396470070
   75: U        SHORT_BINSTRING '\x88Z\x88['
   81: q        BINPUT     5
   83: J        BININT     489281365
   88: U        SHORT_BINSTRING '\x88U\x88O'
   94: q        BINPUT     6
   96: J        BININT     1074075642
  101: U        SHORT_BINSTRING '\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b'
  114: q        BINPUT     7
...
```

On Python 2 the raw pickle looks like
```
    0: c    GLOBAL     'BTrees.IOBTree IOBucket'
   25: q    BINPUT     1
   27: .    STOP
highest protocol among opcodes = 1

   28: (    MARK
   29: (        MARK
   30: J            BININT     231506130
   35: U            SHORT_BINSTRING '\x81x\x84Y'
   41: q            BINPUT     2
   43: J            BININT     231506137
   48: U            SHORT_BINSTRING '\xbe\x84`'
   53: q            BINPUT     3
   55: J            BININT     231506138
   60: U            SHORT_BINSTRING '\xe2\x84a'
   65: q            BINPUT     4
   67: J            BININT     396470070
   72: U            SHORT_BINSTRING '\x88Z\x88['
   78: q            BINPUT     5
   80: J            BININT     489281365
   85: U            SHORT_BINSTRING '\x88U\x88O'
   91: q            BINPUT     6
   93: J            BININT     1074075642
   98: U            SHORT_BINSTRING '\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b'
  111: q            BINPUT     7
...
```

which gets unpickled into a tuple

```
(
(231506130,
'\x81x\x84Y',
231506137,
'\xbe\x84`',
231506138,
'\xe2\x84a',
396470070,
'\x88Z\x88[',
489281365,
'\x88U\x88O',
1074075642,
'\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b',
...
), <persistent reference to the next IOBucket>)
```

I have no idea what this IOBTree contains, but it looks like it's mapping ints to bytestrings.

This would be a perfect opportunity to use a custom decode annotation and mark the attribute as binary, except there's no attribute here.  `IOBucket.__getstate__` returns that tuple, and not a dict mapping attributes to values.

What would be a good way to have zodbupdate --convert-py3 deal with this kind of situation?

**Comment by mgedmin** [comment]
For the record, the broken trees were part of zope.index.text.okapiindex.OkapiIndex, created by zope.catalog.text.TextIndex indexing the `name` attribute of some of my domain objects.  I've no idea why they look like binary garbage.  I've solved the problem by reindexing everything -- now I have a new IOBTree that maps integers to Unicode garbage, but search seems to work great.  (Maybe I just don't understand the data structures.  What does Okapi mean anyway?)

**Comment by davisagli** [comment]
@mgedmin I believe it's using the https://en.wikipedia.org/wiki/Okapi_BM25 function to rank relevance of text query results. We saw something similar with ZCatalog lexicons which use a special "widcode" for compressing lists of integer word ids -- it looks like zope.index also contains a widcode.py so that may be the source of the gibberish here as well. This was my workaround there: https://github.com/zopefoundation/Products.ZCatalog/commit/02296fdc70df43e0d542e2d59f2b024bc3e1e3d3 but reindexing also sounds like a reasonable workaround.

**Comment by mgedmin** [comment]
@davisagli Thanks for the explanation!  Could you also link to your zodbupdate branch that that avoids producing unpickleable pickles due to Unicode decode errors?  (Also, are you running zodbupdate on Python 2 or Python 3?)

**Comment by thefunny42** [comment]
We had the issue with the widcode as well when converting our database, those are stored into strings in Python3, but they should have been bytes. We managed to decode them into string using the encoding "raw-unicode-escape" and we did not need to reindex anything. However, they are difficult to target with zodbupdate (we did that part with a script that we ran before the migration).

**Comment by davisagli** [comment]
@mgedmin I guess you mean the branch that got merged in https://github.com/zopefoundation/zodbupdate/pull/14 (with more explanation there)

**Comment by mgedmin** [comment]
@davisagli I meant the branch you mentioned in #46:

> I have a branch of zodbupdate that lets me specify a default encoding (utf-8) and store anything that couldn't be decoded with that encoding as bytes.

so it's probably the same one as #14.
 
If you were running zodbupdate on Python 3 with the --encoding option, that answers my question.  I was running zodbupdate on Python 2, and it produced pickles that cannot be unpickled on Python 3, so any workarounds in `__setstate__` would not have helped me.

I'm just trying to assemble a working alternative to manual reindexing, because I hate manual steps.
