### ISSUE TITLE
UnicodeDecodeError and AssertionError

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/zodbupdate#27]
Using rb3b31b0db70ebad533cc5b66e0d480d8a3c9b874 for a Plone in-place migration.

However this fails badly under Python 3.7.5:

```bin/zodbupdate --pack --convert-py3 --file var/filestorage/Data.fs
Updating magic marker for var/filestorage/Data.fs
Loaded 1 rename rules from OFS:renames
Loaded 2 decode rules from AccessControl:decodes
Loaded 13 decode rules from OFS:decodes
Loaded 3 decode rules from Products.PythonScripts:decodes
Loaded 1 decode rules from Products.ZopeVersionControl:decodes
An error occured
Traceback (most recent call last):
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/main.py", line 221, in main
    updater()
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/update.py", line 82, in __call__
    new = self.processor.rename(current)
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/serialize.py", line 333, in rename
    data = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 6: ordinal not in range(128)
Stopped processing, due to: 'ascii' codec can't decode byte 0xfd in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/main.py", line 221, in main
    updater()
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/update.py", line 82, in __call__
    new = self.processor.rename(current)
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/serialize.py", line 333, in rename
    data = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 6: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/zodbupdate", line 304, in <module>
    sys.exit(zodbupdate.main.main())
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/src/zodbupdate/src/zodbupdate/main.py", line 225, in main
    raise AssertionError()
AssertionError

```

**Comment by zopyx** [comment]
The error is caused by using Python 3 instead of Python 2  (as documented).
However the script should perhaps check the prequisites.

**Comment by jugmac00** [comment]
Hi Andreas - could you edit your answer? You wrote "Python 3" two times. Just in case anybody else has the same problem.
