### ISSUE TITLE
All builds are broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zodbupdate#32]
https://travis-ci.org/github/zopefoundation/zodbupdate

**Comment by mgedmin** [comment]
All of the failures look like this:

```
Error in test test_skipped_types_are_left_untouched (zodbupdate.tests.Python3Tests)
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python/3.6.7/lib/python3.6/unittest/case.py", line 601, in run
    self.setUp()
  File "/home/travis/build/zopefoundation/zodbupdate/src/zodbupdate/tests.py", line 133, in setUp
    IFactory.__module__ = 'module1.interfaces'
AttributeError: readonly attribute
```

This is caused by zope.interface 5.0.0 making `__module__` a read-only attribute on interfaces.  It can be fixed like this: https://github.com/plone/plone.autoform/pull/39/files
